# Generated by Django 3.2.25 on 2025-03-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='utm',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
