# Generated by Django 3.2.25 on 2025-03-23 10:07

from django.db import migrations, models
import django.db.models.deletion
import promapp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0002_alter_order_utm'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='promapp.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='api_key',
            field=promapp.fields.EncryptedCharField(max_length=255),
        ),
    ]
